### ISSUE TITLE
Can't add someone to group  if already in one

### ISSUE THREAD

**Issue by kngfrank** [CCALI/learnthelaw#120] opened 2016-09-01 17:42 UTC
Can't add someone to group if they already belong to a group.

On dev:

If someone is already in a group:

I logged in as main site admin (kfrank) and tried to add user "kateorgadmin" to the group "ctlawhelp." I got the generic error message saying "The website encountered an unexpected error. Please try again later."

I got an email confirming that kateorgadmin was added successfully to ctlawhelp. 

But kateorgadmin cannot edit any content or see any controls for editing.

When I am logged as kateorgadmin and I look at the organization page, I see that I am able to unsubscribe from the group:
![kateorgadmin](https://cloud.githubusercontent.com/assets/4311947/18177522/932aa8bc-7048-11e6-9dda-4463f8f478d6.PNG)

After tinkering around and trying to add the account to ctlawhelp, I can see kateorgadmin in the list of group members as "pending." But when I try to change the account to active, I get the message again: "The website encountered an unexpected error. Please try again later."

***\* Edit: After multiple attempts to add kateorgadmin to ctlawhelp, the system finally allowed me.

**Comment by kngfrank** [comment] 2016-09-01 17:53
Aaaaaaaand then all the behavior stopped when I tried to replicate the problem.

**Comment by KathyDaniels** [comment] 2016-09-06 15:43
I'm getting this too.  I applied to join the group and got a message that my membership is pending approval.  Kate got the message to make me a group member, but when she tried to add me to the group it told her that I was already in a group and she couldn't add me.  

And then I looked at the "People" section and it showed "Unsubscribe from Group" as above as though I am in the group.  And in the org, I am not listed in the Members and just see the regular classroom display, no option to edit.

**Comment by emasters** [comment] 2016-09-20 18:46
The error being generated is 
`EntityMetadataWrapperException: Invalid data value given. Be sure it matches the required data type and format. in EntityDrupalWrapper->set() (line 737 of /vol/data/ocm/sites/all/modules/entity/includes/entity.wrapper.inc).`

This seems to be a bug in Drupal.

**Comment by emasters** [comment] 2016-09-20 18:52
This is a duplicate of #66. I'm going to close this one.

**Closed as completed by emasters** 2016-09-20 18:52 UTC
Labels: duplicate
